In [4]:
#Se preparan los datos para las consultas de la API

In [1]:
#Se importan las librerias que se van a usar.

import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

%load_ext autoreload
%autoreload 2
import functions
import warnings
warnings.filterwarnings("ignore")

In [6]:
# Se extraen los datos limpios de los archivos CSV
df_games = pd.read_csv("data\output_steam_games.csv") #Contiene inormacion de los juegos de la plataforma

df_users = pd.read_csv("data\oaustralian_users_items.csv") #Contiene informacion sobre los juegos de cada usuario

df_reviews = pd.read_csv('data\oaustralian_user_review.csv') #Contiene informacion sobre las reviews hechas por los usuarios

Se pide hacer un analisis de sentimientos para los comentarios, utilizando la siguiente escala:
 0 es negativo
 1 es neutral o no tiene review
 2 es positivo
  El objetivo es conseguir un producto minimo viable se va a realizar un analisi de sentimiento basico con TextBlob. 
  Dicha libreria usa un sistema de procesamiento de lenguaje natural.

In [7]:
df_reviews["sentiment_analysis"] = df_reviews["reviews_review"].apply(functions.sentimientos)

In [8]:
#Se revisan algunos ejemplos para cada clase de sentimiento

In [9]:
df_reviews[df_reviews["sentiment_analysis"]== 0]

,user_id,user_url,reviews_posted,reviews_item_id,reviews_helpful,reviews_recommend,reviews_review,sentiment_analysis
5,Wackky,http://steamcommunity.com/id/Wackky,2014-05-05,249130,7 of 8 people (88%) found this review helpful,True,This game is Marvellous.,0
7,MeaTCompany,http://steamcommunity.com/id/MeaTCompany,Formato invalido,730,No ratings yet,True,BEST GAME IN THE BLOODY WORLD,0
8,76561198089393905,http://steamcommunity.com/profiles/76561198089...,2015-02-01,72850,3 of 3 people (100%) found this review helpful,True,"Killed the Emperor, nobody cared and got away ...",0
14,DJKamBer,http://steamcommunity.com/id/DJKamBer,2014-07-14,304930,2 of 4 people (50%) found this review helpful,True,"At first, it looked to me that...""Wow, just an...",0
16,76561198043472122,http://steamcommunity.com/profiles/76561198043...,2014-12-19,33440,1 of 3 people (33%) found this review helpful,False,This Game Doesn't Work,0
...,...,...,...,...,...,...,...,...
57357,bmayall,http://steamcommunity.com/id/bmayall,2013-12-07,232010,No ratings yet,True,I wanted this game to be Controller Supported ...,0
57359,adamdacheeseburger139146,http://steamcommunity.com/id/adamdacheeseburge...,2014-02-03,221910,No ratings yet,True,"A first person game which has no guns, no line...",0
57361,kushikushigani,http://steamcommunity.com/id/kushikushigani,2015-12-30,332310,No ratings yet,True,Normally I would hardly play a lego based game...,0
57363,76561198111410893,http://steamcommunity.com/profiles/76561198111...,2014-08-02,304930,No ratings yet,True,Fun game with friends,0
57366,EchoXSilence,http://steamcommunity.com/id/EchoXSilence,Formato invalido,570,0 of 2 people (0%) found this review helpful,False,DOTA 2.normal skill - 2ez for me>high skill - ...,0

In [10]:
df_reviews[df_reviews["sentiment_analysis"]== 1]

,user_id,user_url,reviews_posted,reviews_item_id,reviews_helpful,reviews_recommend,reviews_review,sentiment_analysis
4,maplemage,http://steamcommunity.com/id/maplemage,2014-04-15,211420,35 of 43 people (81%) found this review helpful,True,Git gud,1
6,76561198079601835,http://steamcommunity.com/profiles/76561198079...,Formato invalido,730,0 of 1 people (0%) found this review helpful,True,ZIKA DO BAILE,1
10,76561198077246154,http://steamcommunity.com/profiles/76561198077...,Formato invalido,440,No ratings yet,True,mt bom,1
11,WeiEDKrSat,http://steamcommunity.com/id/WeiEDKrSat,2013-12-25,4000,0 of 1 people (0%) found this review helpful,True,es la rajaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...,1
12,thequeenpanda,http://steamcommunity.com/id/thequeenpanda,2012-06-23,42910,0 of 2 people (0%) found this review helpful,True,MAGICKA *SNORT* *SNORT*,1
...,...,...,...,...,...,...,...,...
57348,haaaagaaaay,http://steamcommunity.com/id/haaaagaaaay,2015-07-14,346900,No ratings yet,True,This is so addicting and i feel like im A LEMO...,1
57352,Skye04,http://steamcommunity.com/id/Skye04,2014-12-24,213610,No ratings yet,True,I'll link you to something that will... encour...,1
57354,mamat08,http://steamcommunity.com/id/mamat08,2013-09-08,219740,No ratings yet,True,Recomendo esse jogo para todos e realmente mui...,1
57355,76561198098137546,http://steamcommunity.com/profiles/76561198098...,2015-12-30,253710,No ratings yet,False,Animal watching/walking sim 10/10,1
57358,2092000666,http://steamcommunity.com/id/2092000666,2013-12-20,105600,No ratings yet,True,",",1

In [11]:
df_reviews[df_reviews["sentiment_analysis"]== 2]

,user_id,user_url,reviews_posted,reviews_item_id,reviews_helpful,reviews_recommend,reviews_review,sentiment_analysis
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,2011-11-05,1250,No ratings yet,True,Simple yet with great replayability. In my opi...,2
1,js41637,http://steamcommunity.com/id/js41637,2014-06-24,251610,15 of 20 people (75%) found this review helpful,True,I know what you think when you see this title ...,2
2,evcentric,http://steamcommunity.com/id/evcentric,Formato invalido,248820,No ratings yet,True,A suitably punishing roguelike platformer. Wi...,2
3,doctr,http://steamcommunity.com/id/doctr,2013-10-14,250320,2 of 2 people (100%) found this review helpful,True,This game... is so fun. The fight sequences ha...,2
9,76561198156664158,http://steamcommunity.com/profiles/76561198156...,Formato invalido,252950,0 of 1 people (0%) found this review helpful,True,love it,2
...,...,...,...,...,...,...,...,...
57356,76561198100193015,http://steamcommunity.com/profiles/76561198100...,2015-08-27,291480,No ratings yet,True,Nice fast paced fps game.,2
57360,76561198107177722,http://steamcommunity.com/profiles/76561198107...,2014-06-27,238460,No ratings yet,True,Its a great game if your up for a challenge or...,2
57362,How51,http://steamcommunity.com/id/How51,2014-08-15,440,No ratings yet,True,TF2 is alot of fun and its really good but the...,2
57364,zaza147,http://steamcommunity.com/id/zaza147,2015-07-31,265630,No ratings yet,True,So Fun!! :D,2
57365,lifeonhigh,http://steamcommunity.com/id/lifeonhigh,2015-12-20,304050,No ratings yet,True,"This game is great. The only thing is,Why cant...",2

In [12]:
#Se guarda el DataFrame en un archivo CSV
archivo = "data/australian_user_review.csv"
df_reviews.to_csv(archivo,index=False, encoding="utf-8")
print("Se guardo el archivo correctamente")

Se guardo el archivo correctamente

In [13]:
#se elimina la columna reviews_review
df_reviews.drop(columns=["reviews_review"],inplace=True)

In [14]:
df_users

,item_id,item_name,playtime_forever,steam_id,items_count,user_id,user_url
0,10,Counter-Strike,6,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
1,20,Team Fortress Classic,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
2,30,Day of Defeat,7,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
3,40,Deathmatch Classic,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
4,50,Half-Life: Opposing Force,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
...,...,...,...,...,...,...,...
5094100,346330,BrainBread 2,0,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5094101,373330,All Is Dust,0,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5094102,388490,One Way To Die: Steam Edition,3,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5094103,521570,You Have 10 Seconds 2,4,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5094104,519140,Minds Eyes,3,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...

In [15]:
df_games

,genres,price,early_access,id,release_year,publisher,app_name,title,developer
0,Action,4.99,False,761140,2018,Kotoshiro,Lost Summoner Kitty,Lost Summoner Kitty,Kotoshiro
1,Casual,4.99,False,761140,2018,Kotoshiro,Lost Summoner Kitty,Lost Summoner Kitty,Kotoshiro
2,Indie,4.99,False,761140,2018,Kotoshiro,Lost Summoner Kitty,Lost Summoner Kitty,Kotoshiro
3,Simulation,4.99,False,761140,2018,Kotoshiro,Lost Summoner Kitty,Lost Summoner Kitty,Kotoshiro
4,Strategy,4.99,False,761140,2018,Kotoshiro,Lost Summoner Kitty,Lost Summoner Kitty,Kotoshiro
...,...,...,...,...,...,...,...,...,...
71546,Indie,1.99,False,610660,2018,Laush Studio,Russian Roads,Russian Roads,Laush Dmitriy Sergeevich
71547,Racing,1.99,False,610660,2018,Laush Studio,Russian Roads,Russian Roads,Laush Dmitriy Sergeevich
71548,Simulation,1.99,False,610660,2018,Laush Studio,Russian Roads,Russian Roads,Laush Dmitriy Sergeevich
71549,Casual,4.99,False,658870,2017,SIXNAILS,EXIT 2 - Directions,EXIT 2 - Directions,"xropi,stev3ns"
71550,Indie,4.99,False,658870,2017,SIXNAILS,EXIT 2 - Directions,EXIT 2 - Directions,"xropi,stev3ns"

In [16]:
df_games.rename(columns= {"id":"item_id"} ,inplace =True)

In [23]:
df_reviews

,user_id,user_url,reviews_posted,reviews_item_id,reviews_helpful,reviews_recommend,sentiment_analysis
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,2011-11-05,1250,No ratings yet,True,2
1,js41637,http://steamcommunity.com/id/js41637,2014-06-24,251610,15 of 20 people (75%) found this review helpful,True,2
2,evcentric,http://steamcommunity.com/id/evcentric,Formato invalido,248820,No ratings yet,True,2
3,doctr,http://steamcommunity.com/id/doctr,2013-10-14,250320,2 of 2 people (100%) found this review helpful,True,2
4,maplemage,http://steamcommunity.com/id/maplemage,2014-04-15,211420,35 of 43 people (81%) found this review helpful,True,1
...,...,...,...,...,...,...,...
57362,How51,http://steamcommunity.com/id/How51,2014-08-15,440,No ratings yet,True,2
57363,76561198111410893,http://steamcommunity.com/profiles/76561198111...,2014-08-02,304930,No ratings yet,True,0
57364,zaza147,http://steamcommunity.com/id/zaza147,2015-07-31,265630,No ratings yet,True,2
57365,lifeonhigh,http://steamcommunity.com/id/lifeonhigh,2015-12-20,304050,No ratings yet,True,2
57366,EchoXSilence,http://steamcommunity.com/id/EchoXSilence,Formato invalido,570,0 of 2 people (0%) found this review helpful,False,0

In [34]:
df_games.head(2)

,genres,price,early_access,item_id,release_year,publisher,app_name,title,developer
0,Action,4.99,False,761140,2018,Kotoshiro,Lost Summoner Kitty,Lost Summoner Kitty,Kotoshiro
1,Casual,4.99,False,761140,2018,Kotoshiro,Lost Summoner Kitty,Lost Summoner Kitty,Kotoshiro

In [35]:
df1 = pd.merge(df_reviews, df_users, how = "inner", on ="user_id")

In [36]:
df2 = pd.merge(df1, df_games, how="inner", on = "item_id")

In [37]:
df2.head(1)

,user_id,user_url_x,reviews_posted,reviews_item_id,reviews_helpful,reviews_recommend,sentiment_analysis,item_id,item_name,playtime_forever,...,items_count,user_url_y,genres,price,early_access,release_year,publisher,app_name,title,developer
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,2011-11-05,1250,No ratings yet,True,2,10,Counter-Strike,6,...,277,http://steamcommunity.com/profiles/76561197970...,Action,9.99,False,2000,Valve,Counter-Strike,Counter-Strike,Valve

In [38]:
data = df2[["release_year","genres", "playtime_forever" ,"user_id", "item_id","item_name" ,"sentiment_analysis" ,"reviews_recommend" ,"reviews_posted"]]

In [39]:
data = data.dropna()

In [40]:
data["reviews_posted"] = pd.to_datetime(data["reviews_posted"],errors ="coerce")
data["reviews_year"] = data["reviews_posted"].dt.year

In [41]:
data

,release_year,genres,playtime_forever,user_id,item_id,item_name,sentiment_analysis,reviews_recommend,reviews_posted,reviews_year
0,2000,Action,6,76561197970982479,10,Counter-Strike,2,True,2011-11-05,2011.0
1,2000,Action,6,76561197970982479,10,Counter-Strike,2,True,2011-07-15,2011.0
2,2000,Action,6,76561197970982479,10,Counter-Strike,2,True,2011-04-21,2011.0
3,2000,Action,0,js41637,10,Counter-Strike,2,True,2014-06-24,2014.0
4,2000,Action,0,js41637,10,Counter-Strike,0,True,2013-09-08,2013.0
...,...,...,...,...,...,...,...,...,...,...
11854181,2016,Indie,0,inven,433920,Aveyond 4: Shadow Of The Mist,1,True,2015-04-06,2015.0
11854182,2016,RPG,0,inven,433920,Aveyond 4: Shadow Of The Mist,1,True,2015-04-06,2015.0
11854183,2015,Action,226,76561198134165301,352760,Kaiju Panic,1,True,NaT,NaN
11854184,2015,Indie,226,76561198134165301,352760,Kaiju Panic,1,True,NaT,NaN
11854185,2015,Strategy,226,76561198134165301,352760,Kaiju Panic,1,True,NaT,NaN

In [42]:
data.drop("reviews_posted",axis=1,inplace=True)

In [43]:
data

,release_year,genres,playtime_forever,user_id,item_id,item_name,sentiment_analysis,reviews_recommend,reviews_year
0,2000,Action,6,76561197970982479,10,Counter-Strike,2,True,2011.0
1,2000,Action,6,76561197970982479,10,Counter-Strike,2,True,2011.0
2,2000,Action,6,76561197970982479,10,Counter-Strike,2,True,2011.0
3,2000,Action,0,js41637,10,Counter-Strike,2,True,2014.0
4,2000,Action,0,js41637,10,Counter-Strike,0,True,2013.0
...,...,...,...,...,...,...,...,...,...
11854181,2016,Indie,0,inven,433920,Aveyond 4: Shadow Of The Mist,1,True,2015.0
11854182,2016,RPG,0,inven,433920,Aveyond 4: Shadow Of The Mist,1,True,2015.0
11854183,2015,Action,226,76561198134165301,352760,Kaiju Panic,1,True,NaN
11854184,2015,Indie,226,76561198134165301,352760,Kaiju Panic,1,True,NaN
11854185,2015,Strategy,226,76561198134165301,352760,Kaiju Panic,1,True,NaN

In [44]:
data.dropna(inplace=True)

In [45]:
functions.tipo_dato(data)

         nombre_campo          tipo_dato  nulo  no_nulo%  nulo%
0        release_year    [<class 'str'>]     0     100.0    0.0
1              genres    [<class 'str'>]     0     100.0    0.0
2    playtime_forever    [<class 'int'>]     0     100.0    0.0
3             user_id    [<class 'str'>]     0     100.0    0.0
4             item_id    [<class 'int'>]     0     100.0    0.0
5           item_name    [<class 'str'>]     0     100.0    0.0
6  sentiment_analysis    [<class 'int'>]     0     100.0    0.0
7   reviews_recommend   [<class 'bool'>]     0     100.0    0.0
8        reviews_year  [<class 'float'>]     0     100.0    0.0

In [47]:
file_path_gzip = "data\data_export_api_gzip.parquet"
data.to_parquet(file_path_gzip, engine="pyarrow", compression="gzip")